owner: DATAIMPACTING
repo: status

sites:
  - name: update.dataimpact.ing
    url: https://update.dataimpact.ing/
  - name: brand.dataimpact.ing
    url: https://brand.dataimpact.ing/
  - name: gallery.dataimpact.ing
    url: https://gallery.dataimpact.ing/
  - name: go.dataimpact.ing
    url: https://go.dataimpact.ing/
  - name: share.dataimpact.ing
    url: https://share.dataimpact.ing/
    
status-website:
  cname: status.dataimpact.ing
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status | DATA IMPACT
  introTitle: "**Status** for DATA IMPACT"
  introMessage: 데이터임팩트 웹모니터
  navbar:
    - title: Website
      href: https://dataimpact.ing
    - title: Update
      href: https://update.dataimpact.ing
    - title: Discord
      href: https://discord.dataimpact.ing
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
