name: Keepalive Workflow

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
        with:
          gh_token: ${{ secrets.GH_PAT }}
